name: Ixjok

services:
  ixjok.server:
    container_name: Ixjok-Server:v1-alpine3.22
    build:
      context: ./
      dockerfile: ./Ixjok.Server/Dockerfile
    ports:
      - 5411:5411
    environment:
      - CONNECTION=server=200.0.20.1;ports=5432;database=Ixjok;user id=${POST_USER};password=${POST_PASS};
    networks:
      ixjok:
        ipv4_address: 200.0.20.1
  ixjok.database:
    image: postgres:18-alpine3.22
    container_name: Ixjok-Database
    environment:
      - POSTGRES_PASSWORD=${POST_PASS}
      - POSTGRES_USER=${POST_USER}
    ports:
      - 5410:5432
    expose:
      - 5432
    volumes:
      - ixjok:/var/lib/postgres
    networks:
      ixjok:
        ipv4_address: 200.0.20.0

volumes:
  ixjok:
    external: false

networks:
  ixjok:
    internal: false
    ipam:
      config:
        - subnet: 200.0.20.0/10
          gateway: 200.0.20.10