name: Ixjok

services:
  ixjok.server:
    container_name: ixjok-server
    image: ixjok-server:v1-alpine3.22
    build:
      context: ./
      dockerfile: ./Ixjok.Server/Dockerfile
    ports:
      - 5411:5411
    environment:
      - CONNECTION=server=200.0.0.1;port=5432;database=Ixjok;user id=${POST_USER};password=${POST_PASS};
      - DOTNET_URLS=http://200.0.0.2:5411
      - BEARER_KEY=${ASP_KEY_BEARER}
    networks:
      ixjok:
        ipv4_address: 200.0.0.2
    depends_on:
      - ixjok.database
    develop:
      watch:
        - path: ./Ixjok.Server
          action: rebuild
          target: ./Ixjok.Server/
          # initial_sync: true
  ixjok.database:
    image: postgres:18-alpine3.22
    container_name: Ixjok-database
    environment:
      - POSTGRES_PASSWORD=${POST_PASS}
      - POSTGRES_USER=${POST_USER}
    ports:
      - 5410:5432
    expose:
      - 5432
    volumes:
      - ixjok:/var/lib/postgres
    networks:
      ixjok:
        ipv4_address: 200.0.0.1

volumes:
  ixjok:
    external: false

networks:
  ixjok:
    internal: false
    ipam:
      config:
        - subnet: 200.0.0.0/10
          gateway: 200.0.0.9