<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>
    <!-- <UseMonoRuntime>false</UseMonoRuntime> -->
    <GenerateImplicitNamespacesDeclaration>false</GenerateImplicitNamespacesDeclaration>
    <Deterministic>true</Deterministic>
    <HotReloadAutoRestar>true</HotReloadAutoRestar>
  </PropertyGroup>
</Project>
